### ISSUE TITLE
Extruder: Upper idler nut trap intersects filament path

### ISSUE THREAD

**Issue by rparrett** [UltiBots/K250VS#1]
In the new extruder design introduced by 208ae8aec9a1b49e120d56986372f4b6305caf74.

Just barely, but I did notice some increased friction on the filament after installing the jam nut in the extruder that I just printed.

![extuderbug](https://cloud.githubusercontent.com/assets/200550/13561230/c80e40f4-e3e7-11e5-8f5d-91b0aa08afb7.PNG)

**Comment by Verohomie** [comment]
Try the untested v6.6 STLs in the experimental folder. If all is OK, will make them current.

Good catch - Brad

**Comment by rparrett** [comment]
So I was actually printing this version to see if I could coax a j-head onto it by using m2 hardware instead of m3 hardware or something like that. But that doesn't seem like a good idea.

So unfortunately I wouldn't be able to give any feedback as to whether this is a nice working extruder.

Any chance of maintaining a j-head compatible version?

**Comment by Verohomie** [comment]
Added an untested J-Head version that uses M3 screws for compatibility with our Micro Extruder Hardware Kits.
